// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/mainService.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Struct message Client send to Server or Server send back to Client
type KeyWordC struct {
	ClientString         string   `protobuf:"bytes,1,opt,name=clientString,proto3" json:"clientString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyWordC) Reset()         { *m = KeyWordC{} }
func (m *KeyWordC) String() string { return proto.CompactTextString(m) }
func (*KeyWordC) ProtoMessage()    {}
func (*KeyWordC) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6104a6250fa0a57, []int{0}
}

func (m *KeyWordC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyWordC.Unmarshal(m, b)
}
func (m *KeyWordC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyWordC.Marshal(b, m, deterministic)
}
func (m *KeyWordC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyWordC.Merge(m, src)
}
func (m *KeyWordC) XXX_Size() int {
	return xxx_messageInfo_KeyWordC.Size(m)
}
func (m *KeyWordC) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyWordC.DiscardUnknown(m)
}

var xxx_messageInfo_KeyWordC proto.InternalMessageInfo

func (m *KeyWordC) GetClientString() string {
	if m != nil {
		return m.ClientString
	}
	return ""
}

type KeyWordS struct {
	ClientString         string   `protobuf:"bytes,1,opt,name=clientString,proto3" json:"clientString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyWordS) Reset()         { *m = KeyWordS{} }
func (m *KeyWordS) String() string { return proto.CompactTextString(m) }
func (*KeyWordS) ProtoMessage()    {}
func (*KeyWordS) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6104a6250fa0a57, []int{1}
}

func (m *KeyWordS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyWordS.Unmarshal(m, b)
}
func (m *KeyWordS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyWordS.Marshal(b, m, deterministic)
}
func (m *KeyWordS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyWordS.Merge(m, src)
}
func (m *KeyWordS) XXX_Size() int {
	return xxx_messageInfo_KeyWordS.Size(m)
}
func (m *KeyWordS) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyWordS.DiscardUnknown(m)
}

var xxx_messageInfo_KeyWordS proto.InternalMessageInfo

func (m *KeyWordS) GetClientString() string {
	if m != nil {
		return m.ClientString
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyWordC)(nil), "protos.keyWordC")
	proto.RegisterType((*KeyWordS)(nil), "protos.keyWordS")
}

func init() { proto.RegisterFile("protos/mainService.proto", fileDescriptor_d6104a6250fa0a57) }

var fileDescriptor_d6104a6250fa0a57 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x4d, 0xcc, 0xcc, 0x0b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03,
	0x0b, 0x09, 0xb1, 0x41, 0x64, 0x94, 0xf4, 0xb8, 0x38, 0xb2, 0x53, 0x2b, 0xc3, 0xf3, 0x8b, 0x52,
	0x9c, 0x85, 0x94, 0xb8, 0x78, 0x92, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x82, 0x4b, 0x8a, 0x32, 0xf3,
	0xd2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x50, 0xc4, 0x90, 0xd4, 0x07, 0x13, 0xa3, 0xde,
	0xc8, 0x81, 0x8b, 0x1b, 0xc9, 0x72, 0x21, 0x43, 0x08, 0xd7, 0x1b, 0x62, 0x84, 0x90, 0x00, 0xc4,
	0x35, 0xc5, 0x7a, 0x30, 0x37, 0x48, 0xa1, 0x8b, 0x04, 0x3b, 0xe9, 0x47, 0xe9, 0xa6, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x27, 0xe6, 0x65, 0x94, 0x64, 0x64, 0xa6, 0x96,
	0x58, 0x1a, 0x25, 0x95, 0x66, 0xe8, 0x17, 0xa7, 0x16, 0x95, 0xa5, 0x16, 0xc5, 0x27, 0x65, 0xa6,
	0xa7, 0x67, 0x26, 0xeb, 0x43, 0x74, 0x26, 0x41, 0xbc, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x64, 0xd6, 0x4e, 0x1d, 0xfd, 0x00, 0x00, 0x00,
}
