// Code generated by protoc-gen-go. DO NOT EDIT.
// source: check.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MClient struct {
	StrClient            string   `protobuf:"bytes,1,opt,name=strClient,proto3" json:"strClient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MClient) Reset()         { *m = MClient{} }
func (m *MClient) String() string { return proto.CompactTextString(m) }
func (*MClient) ProtoMessage()    {}
func (*MClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d3c606fb107336, []int{0}
}

func (m *MClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MClient.Unmarshal(m, b)
}
func (m *MClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MClient.Marshal(b, m, deterministic)
}
func (m *MClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MClient.Merge(m, src)
}
func (m *MClient) XXX_Size() int {
	return xxx_messageInfo_MClient.Size(m)
}
func (m *MClient) XXX_DiscardUnknown() {
	xxx_messageInfo_MClient.DiscardUnknown(m)
}

var xxx_messageInfo_MClient proto.InternalMessageInfo

func (m *MClient) GetStrClient() string {
	if m != nil {
		return m.StrClient
	}
	return ""
}

type MServer struct {
	StrServer            string   `protobuf:"bytes,1,opt,name=strServer,proto3" json:"strServer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MServer) Reset()         { *m = MServer{} }
func (m *MServer) String() string { return proto.CompactTextString(m) }
func (*MServer) ProtoMessage()    {}
func (*MServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8d3c606fb107336, []int{1}
}

func (m *MServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MServer.Unmarshal(m, b)
}
func (m *MServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MServer.Marshal(b, m, deterministic)
}
func (m *MServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MServer.Merge(m, src)
}
func (m *MServer) XXX_Size() int {
	return xxx_messageInfo_MServer.Size(m)
}
func (m *MServer) XXX_DiscardUnknown() {
	xxx_messageInfo_MServer.DiscardUnknown(m)
}

var xxx_messageInfo_MServer proto.InternalMessageInfo

func (m *MServer) GetStrServer() string {
	if m != nil {
		return m.StrServer
	}
	return ""
}

func init() {
	proto.RegisterType((*MClient)(nil), "protos.mClient")
	proto.RegisterType((*MServer)(nil), "protos.mServer")
}

func init() { proto.RegisterFile("check.proto", fileDescriptor_d8d3c606fb107336) }

var fileDescriptor_d8d3c606fb107336 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0x48, 0x4d,
	0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xea, 0x5c, 0xec,
	0xb9, 0xce, 0x39, 0x99, 0xa9, 0x79, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0xc5, 0x25, 0x45, 0x10, 0x8e,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42, 0x00, 0xac, 0x30, 0x38, 0xb5, 0xa8, 0x2c, 0xb5,
	0x08, 0xaa, 0x10, 0xc2, 0x41, 0x52, 0x08, 0x11, 0x30, 0xb2, 0xe7, 0xe2, 0x01, 0x5b, 0x04, 0xe2,
	0x66, 0x26, 0xa7, 0x0a, 0xe9, 0x43, 0x2d, 0x0e, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x11, 0xe2, 0x87,
	0x38, 0xa0, 0x58, 0x0f, 0x6a, 0xad, 0x14, 0x42, 0x00, 0x62, 0x80, 0x13, 0x57, 0x14, 0x87, 0x9e,
	0x35, 0x44, 0x2c, 0x09, 0xe2, 0x4c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x29, 0xdc,
	0xc8, 0xbc, 0x00, 0x00, 0x00,
}
